### ISSUE TITLE
Representable: ArgumentError: wrong number of arguments (given 0, expected 2..3)

### ISSUE THREAD

**Issue by KurtRMueller** [trailblazer/reform#379]
Hey all,

This error occurs when I upgraded `reform` from `2.1.0` to `2.2.1` and `reform-rails` from `0.1.0` to `0.1.4`. This error does not occur if I rollback the gem versions. 

The error is being thrown from the `representable` gem, version `3.0.0`, in `lib\representable\serializer.rb` at line 6:

``` ruby
GetValue = ->(input, options) { options[:binding].send(:exec_context, options).send(options[:binding].getter) }
```

I think it has something to do with `OpenStruct`. I'm not quite sure why `send` can't be used to access the getter method. Notice below that after I directly call the `test` method, I can run the `options[:binding].send(:exec_context, options).send(options[:binding].getter)` without any errors being thrown.

``` ruby
options[:binding].send(:exec_context, options)
# => #<OpenStruct language_id="b40ae7f5-93b8-41df-b928-401bcb9ba557", type="ReadingTestAttempt", student_emplid="69246161", hs_years_studying_language=2, whitelisted_ip_id="b1d5bad8-3cce-45f1-a26a-d5dedfbd65a9", test=#<Test id: "10c3db11-db14-49b5-ab8b-59e4a200ff49", type: "reading", created_at: "2016-07-05 20:57:52", updated_at: "2016-07-05 20:57:52", testing_criteria: {"ability_estimate_limit"=>5, "change_score_limit"=>1.0, "convergence_criterion"=>0.01, "cutoff_hours"=>24, "difficulty_width"=>0.1, "extreme_score_adjustment"=>0.3, "initial"=>{"ability_estimate"=>0.0, "difficulty_width"=>0.5}, "max_difficulty_jump"=>1.0, "minimum_size_of_item_pool"=>10, "time_limit_seconds"=>1800, "min_num_items"=>8, "target"=>{"probability"=>0.6, "se"=>0.66}}, supplanted_at: nil, scoring_criteria: {"mean"=>20.0, "sd"=>3.0, "min"=>5.0, "max"=>35.0}>, cutoff_at=Wed, 06 Jul 2016 21:12:48 UTC +00:00>

options[:binding].getter
# => "test"

options[:binding].send(:exec_context, options).send(options[:binding].getter)
# => ArgumentError: wrong number of arguments (given 0, expected 2..3)

options[:binding].send(:exec_context, options).test
# => #<Test:0x007ff8b9fc7560
 id: "10c3db11-db14-49b5-ab8b-59e4a200ff49",
 type: "reading",
 created_at: Tue, 05 Jul 2016 20:57:52 UTC +00:00,
 updated_at: Tue, 05 Jul 2016 20:57:52 UTC +00:00,
 testing_criteria:
  {"ability_estimate_limit"=>5,
   "change_score_limit"=>1.0,
   "convergence_criterion"=>0.01,
   "cutoff_hours"=>24,
   "difficulty_width"=>0.1,
   "extreme_score_adjustment"=>0.3,
   "initial"=>{"ability_estimate"=>0.0, "difficulty_width"=>0.5},
   "max_difficulty_jump"=>1.0,
   "minimum_size_of_item_pool"=>10,
   "time_limit_seconds"=>1800,
   "min_num_items"=>8,
   "target"=>{"probability"=>0.6, "se"=>0.66}},
 supplanted_at: nil,
 scoring_criteria: {"mean"=>20.0, "sd"=>3.0, "min"=>5.0, "max"=>35.0}>

options[:binding].send(:exec_context, options).send("test")
# => #<Test:0x007ff8b9fc7560
 id: "10c3db11-db14-49b5-ab8b-59e4a200ff49",
 type: "reading",
 created_at: Tue, 05 Jul 2016 20:57:52 UTC +00:00,
 updated_at: Tue, 05 Jul 2016 20:57:52 UTC +00:00,
 testing_criteria:
  {"ability_estimate_limit"=>5,
   "change_score_limit"=>1.0,
   "convergence_criterion"=>0.01,
   "cutoff_hours"=>24,
   "difficulty_width"=>0.1,
   "extreme_score_adjustment"=>0.3,
   "initial"=>{"ability_estimate"=>0.0, "difficulty_width"=>0.5},
   "max_difficulty_jump"=>1.0,
   "minimum_size_of_item_pool"=>10,
   "time_limit_seconds"=>1800,
   "min_num_items"=>8,
   "target"=>{"probability"=>0.6, "se"=>0.66}},
 supplanted_at: nil,
 scoring_criteria: {"mean"=>20.0, "sd"=>3.0, "min"=>5.0, "max"=>35.0}>

options[:binding].send(:exec_context, options).send(options[:binding].getter)
# => #<Test:0x007ff8bb39d1c0
 id: "10c3db11-db14-49b5-ab8b-59e4a200ff49",
 type: "reading",
 created_at: Tue, 05 Jul 2016 20:57:52 UTC +00:00,
 updated_at: Tue, 05 Jul 2016 20:57:52 UTC +00:00,
 testing_criteria:
  {"ability_estimate_limit"=>5,
   "change_score_limit"=>1.0,
   "convergence_criterion"=>0.01,
   "cutoff_hours"=>24,
   "difficulty_width"=>0.1,
   "extreme_score_adjustment"=>0.3,
   "initial"=>{"ability_estimate"=>0.0, "difficulty_width"=>0.5},
   "max_difficulty_jump"=>1.0,
   "minimum_size_of_item_pool"=>10,
   "time_limit_seconds"=>1800,
   "min_num_items"=>8,
   "target"=>{"probability"=>0.6, "se"=>0.66}},
 supplanted_at: nil,
 scoring_criteria: {"mean"=>20.0, "sd"=>3.0, "min"=>5.0, "max"=>35.0}>

```

Please let me know if you have any questions/concerns. Thank you for all the hard work you do. Hopefully I can bang on this and submit a pr. Fingers crossed.

Kurt

**Comment by apotonick** [comment]
Please paste the top 20 lines of the stacktrace.

**Comment by KurtRMueller** [comment]
Hey Nick,

I have two stack traces... one from when I'm running a rake task and the other is from the console. I'll paste both:

From the rake task:
```
/Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/serializer.rb:7:in `test': wrong number of arguments (given 0, expected 2..3) (ArgumentError)
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/serializer.rb:7:in `block in <module:Representable>'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/pipeline.rb:18:in `evaluate'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/pipeline.rb:10:in `block in call'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `each'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `inject'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/pipeline.rb:9:in `call'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/binding.rb:32:in `compile_fragment'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable.rb:52:in `block in call'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable.rb:50:in `each'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable.rb:50:in `call'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable.rb:69:in `representable_map!'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable.rb:44:in `create_representation_with'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/hash.rb:34:in `to_hash'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/disposable-0.3.1/lib/disposable/twin/sync.rb:77:in `to_nested_hash'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/reform-rails-0.1.4/lib/reform/form/active_record.rb:24:in `to_nested_hash'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/reform-2.2.1/lib/reform/validation.rb:36:in `valid?'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/reform-2.2.1/lib/reform/contract/validate.rb:18:in `validate!'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/reform-2.2.1/lib/reform/contract/validate.rb:10:in `validate'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/reform-2.2.1/lib/reform/form/validate.rb:23:in `validate'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/trailblazer-1.1.1/lib/trailblazer/operation.rb:146:in `validate_contract'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/trailblazer-1.1.1/lib/trailblazer/operation.rb:136:in `validate'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/trailblazer-1.1.1/lib/trailblazer/operation/model.rb:36:in `validate'
	from /Users/mueller.128/repos/asctech/multicat/app/operations/reading_test_attempt/create.rb:43:in `process'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/trailblazer-1.1.1/lib/trailblazer/operation.rb:70:in `run'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/trailblazer-1.1.1/lib/trailblazer/operation.rb:34:in `call'
	from /Users/mueller.128/repos/asctech/multicat/lib/dummy/attempt.rb:114:in `reading_attempt'
	from /Users/mueller.128/repos/asctech/multicat/lib/dummy/attempt.rb:101:in `take!'
	from /Users/mueller.128/repos/asctech/multicat/lib/dummy/attempt.rb:56:in `by_random_guesser'
	from /Users/mueller.128/repos/asctech/multicat/lib/dummy/attempt.rb:70:in `block in by_multiple_speakers'
	from /Users/mueller.128/repos/asctech/multicat/lib/dummy/attempt.rb:70:in `fork'
	from /Users/mueller.128/repos/asctech/multicat/lib/dummy/attempt.rb:70:in `by_multiple_speakers'
	from /Users/mueller.128/repos/asctech/multicat/lib/tasks/dev/populate/test_attempts.rake:6:in `block (4 levels) in <top (required)>'
	from /Users/mueller.128/repos/asctech/multicat/lib/tasks/dev/populate/test_attempts.rake:5:in `times'
	from /Users/mueller.128/repos/asctech/multicat/lib/tasks/dev/populate/test_attempts.rake:5:in `each'
	from /Users/mueller.128/repos/asctech/multicat/lib/tasks/dev/populate/test_attempts.rake:5:in `block (3 levels) in <top (required)>'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
	from /Users/mueller.128/repos/asctech/multicat/lib/tasks/dev/populate.rake:14:in `block (3 levels) in <top (required)>'
	from /Users/mueller.128/repos/asctech/multicat/lib/tasks/dev/populate.rake:7:in `each'
	from /Users/mueller.128/repos/asctech/multicat/lib/tasks/dev/populate.rake:7:in `block (2 levels) in <top (required)>'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
	from /Users/mueller.128/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
	from /Users/mueller.128/repos/asctech/multicat/bin/rake:10:in `<top (required)>'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/command_wrapper.rb:40:in `call'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
	from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/mueller.128/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/mueller.128/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

From the console:

```
Dummy::Attempt.by_semifluent_speaker
  WhitelistedIp Load (1.4ms)  SELECT "whitelisted_ips".* FROM "whitelisted_ips" WHERE ("whitelisted_ips"."locks_at" >= '2016-07-05 21:56:23.920598')  ORDER BY "whitelisted_ips"."created_at" DESC
   (0.2ms)  BEGIN
  User Exists (1.6ms)  SELECT  1 AS one FROM "users" WHERE "users"."emplid" = '07241078' LIMIT 1
  User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE "users"."name_n" = 'rath.863' LIMIT 1
  User Exists (1.1ms)  SELECT  1 AS one FROM "users" WHERE "users"."emails" = '{rath.863@osu.edu}' LIMIT 1
  SQL (1.0ms)  INSERT INTO "users" ("emplid", "name_n", "first_name", "last_name", "emails", "birthdate", "highschool", "graduation", "current_sign_in_ip", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"  [["emplid", "07241078"], ["name_n", "rath.863"], ["first_name", "Dejah"], ["last_name", "Rath"], ["emails", "{rath.863@osu.edu}"], ["birthdate", "1996-07-05"], ["highschool", "Northern South Dakota University"], ["graduation", "2014-07-05"], ["current_sign_in_ip", "210.155.35.119/32"], ["created_at", "2016-07-05 21:56:24.305750"], ["updated_at", "2016-07-05 21:56:24.305750"]]
   (1.0ms)  COMMIT
  Language Load (0.9ms)  SELECT "languages".* FROM "languages"
  TestAttempt Exists (1.0ms)  SELECT  1 AS one FROM "test_attempts" WHERE "test_attempts"."dropped_at" IS NULL AND "test_attempts"."student_emplid" = $1 AND "test_attempts"."type" = $2 AND "test_attempts"."language_id" IS NULL AND "test_attempts"."dropped_at" IS NULL LIMIT 1  [["student_emplid", "07241078"], ["type", "ReadingTestAttempt"]]
  Test Load (0.7ms)  SELECT  "tests".* FROM "tests" WHERE "tests"."supplanted_at" IS NULL AND "tests"."type" = $1  ORDER BY "tests"."created_at" DESC LIMIT 1  [["type", "reading"]]
ArgumentError: wrong number of arguments (given 0, expected 2..3)
from /Users/mueller.128/.rvm/gems/ruby-2.3.1@multicat/gems/representable-3.0.0/lib/representable/serializer.rb:7:in `test'
```

**Comment by KurtRMueller** [comment]
I wonder if `test` is a reserved word for either `OpenStruct`, `Representable`, or `Reform`.

**Comment by apotonick** [comment]
What's `test`? It looks like you set the `:exec_context` to the wrong object.

**Comment by apotonick** [comment]
What representable version were you using before the update? It would've been 2.3 in compat mode. So I'm guessing you didn't completely update to the 3.0 API? :cactus:

**Comment by KurtRMueller** [comment]
`Test` in this case refers to a computer adaptive test a student takes when they enter a university. I specifically am using `Operation` and `Reform`. I'll answer your other questions after this.

Here's the contract I'm currently using:

```
class ReadingTestAttempt::CreateForm < Reform::Form
  property :language_id,
           validates: { presence: true }

  property :type,
           default: 'ReadingTestAttempt',
           readable: false,
           validates: { presence: true }

  property :student_emplid,
           readable: false,
           validates: { presence: true }

  property :hs_years_studying_language,
           validates: { presence: true,
                        inclusion: { in: (1..4).to_a } }

  property :whitelisted_ip_id,
           validates: { presence: true }

  property :test,
           default:   -> { Test.most_recent.reading.first },
           readable:  false,
           validates: { presence: true }

  property :cutoff_at,
           default:   -> { Time.zone.now + test.cutoff_hours.hours },
           readable:  false,
           validates: { presence: true }
end

```

**Comment by KurtRMueller** [comment]
`representable` has been at `3.0.0` for awhile now.

**Comment by apotonick** [comment]
Then, it's super weird, because Reform 2.2 is really Reform 2.1 without Rails, which you bring via `reform-rails`?!

Maybe chat on Gitter?

**Comment by KurtRMueller** [comment]
I'm in the `Trailblazer` gitter.

**Comment by fran-worley** [comment]
@KurtRMueller any updates here? Did you manage to resolve the problem on Gitter?
