### ISSUE TITLE
Forwarding to private method OpenStruct#persisted?

### ISSUE THREAD

**Issue by anthony-robin** [trailblazer/reform#430]
I am using the gem for a contact form. As a contact form doesn’t have an associated model to persist data, I instantiate my form object like this:

```ruby
@form = ContactForm.new
```
```ruby
class ContactForm < ApplicationForm
  properties :name, :email, :message, :nickname

  def initialize
    super OpenStruct.new
  end
end
```

But this gives me the following logs when I access the form page:
```
/.rvm/gems/ruby-2.4.0/gems/simple_form-3.4.0/lib/simple_form/action_view_extensions/form_helper.rb:61:in 
`simple_form_css_class': #<Module:0x007f925a0021e0>#persisted? at /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 
forwarding to private method OpenStruct#persisted?

/.rvm/gems/ruby-2.4.0/gems/actionview-5.0.2/lib/action_view/helpers/form_helper.rb:462:in `apply_form_for_options!': 
#<Module:0x007f925a0021e0>#persisted? at /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 
forwarding to private method OpenStruct#persisted?

/.rvm/gems/ruby-2.4.0/gems/actionview-5.0.2/lib/action_view/record_identifier.rb:106:in `record_key_for_dom_id': 
#<Module:0x007f925a0021e0>#to_key at /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 
forwarding to private method OpenStruct#to_key

/.rvm/gems/ruby-2.4.0/gems/actionpack-5.0.2/lib/action_dispatch/routing/polymorphic_routes.rb:250:in `handle_model': 
#<Module:0x007f925a0021e0>#persisted? at /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 
forwarding to private method OpenStruct#persisted?

/.rvm/gems/ruby-2.4.0/gems/actionview-5.0.2/lib/action_view/helpers/form_helper.rb:1873:in `submit_default_value': 
#<Module:0x007f925a0021e0>#persisted? at /.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 
forwarding to private method OpenStruct#persisted?
```

Is OpenStruct the best way to deal with form without models ? Is it a Ruby version issue ?

**Stack**:
- Rails 5.0.2
- Ruby 2.4.0
- Reform 2.2.4
- SimpleForm 3.4.0

**Comment by apotonick** [comment]
It's a Rails problem since the form helper simply assumes this is an `ActiveModel` object. You can add a `persisted?` method to your form to prevent it.
