### ISSUE TITLE
form.errors raises when custom validation rule on collection doesn't pass

### ISSUE THREAD

**Issue by lastobelus** [trailblazer/reform#436]
### Complete Description of Issue

`form.errors` raises in `lib/reform/result.rb:filter_for` when a collection is validated against a custom predicate that fails.

This is due to the recursive collection of errors, so `form.to_result.errors` doesn't exhibit the error.

### Steps to reproduce
```ruby
require 'rails_helper'

context 'collection with validation rule' do

  Song   = Struct.new(:title, :enabled)
  Album  = Struct.new(:title, :songs)

  class AlbumForm < Reform::Form
    property :title

    collection :songs, virtual: true, populate_if_empty: Song do
      property :title
      property :enabled
    end

    validation with: {form: true} do
      configure do
        config.messages_file = Rails.root.join('spec', 'fixtures', 'dry-en.yml')
        def has_a_song?(value)
          value.any? { |el| el && el[:enabled] }
        end
      end

      required(:songs).filled(:has_a_song?)
    end
  end
  it "has an error when no songs enabled" do
    form = AlbumForm.new(Album.new(nil, []))
    form.songs = []
    expect(
      form.validate(
        "songs_attributes" => {
          "0" => {"title" => "One", "enabled" => false},
          "1" => {"title" => "Two", "enabled" => false},
          "2" => {"title" => "Three", "enabled" => false}
        }
      )
    ).to be false
    expect(form.songs.size).to eq(3)

    # raises!
    expect(form.errors.messages).to include(:songs => ["must have at least one enabled song"])

    # ok
    expect(form.to_result.errors).to include(:songs => ["must have at least one enabled song"])
  end

end
```

### System configuration
**Reform version**: 2.3.0rc1

### Full Backtrace of Exception (if any)

```
1) collection with validation rule has an error when no songs enabled
   Failure/Error: expect(form.errors.messages).to include(:songs => ["must have at least one enabled song"])

   TypeError:
     no implicit conversion of String into Hash
   # reform-0753ac23c0aa/lib/reform/result.rb:24:in `merge'
   # reform-0753ac23c0aa/lib/reform/result.rb:24:in `block in filter_for'
   # reform-0753ac23c0aa/lib/reform/result.rb:24:in `each'
   # reform-0753ac23c0aa/lib/reform/result.rb:24:in `inject'
   # reform-0753ac23c0aa/lib/reform/result.rb:24:in `filter_for'
   # reform-0753ac23c0aa/lib/reform/result.rb:17:in `messages'
   # reform-0753ac23c0aa/lib/reform/errors.rb:15:in `block in <class:Errors>'
   # reform-0753ac23c0aa/lib/reform/errors.rb:20:in `block (3 levels) in <class:Errors>'
   # disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `block in collection!'
   # disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `each'
   # disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `each_with_index'
   # disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `each'
   # disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `collect'
   # disposable-0.4.3/lib/disposable/twin/property_processor.rb:24:in `collection!'
   # disposable-0.4.3/lib/disposable/twin/property_processor.rb:16:in `call'
   # reform-0753ac23c0aa/lib/reform/errors.rb:18:in `block (2 levels) in <class:Errors>'
   # disposable-0.4.3/lib/disposable/twin/definitions.rb:27:in `block in each'
   # disposable-0.4.3/lib/disposable/twin/definitions.rb:27:in `each'
   # disposable-0.4.3/lib/disposable/twin/definitions.rb:27:in `each'
   # reform-0753ac23c0aa/lib/reform/errors.rb:17:in `block in <class:Errors>'
   # reform-0753ac23c0aa/lib/reform/errors.rb:9:in `initialize'
   # reform-0753ac23c0aa/lib/reform/contract/validate.rb:16:in `new'
   # reform-0753ac23c0aa/lib/reform/contract/validate.rb:16:in `errors'
   # ./spec/forms/custom_predicate_collection.rb:42:in `block (2 levels) in <top (required)>'
   # ./spec/spec_helper.rb:51:in `block (2 levels) in <top (required)>'
```

**Comment by lastobelus** [comment]
can't figure out a workaround for this, so that I can use my form with `form_for`/`bootstrap_form_for` -- I thought to try overriding `errors` to return `to_result` which works for a one-level form, but fails when it gets to the form objects that make up the collection items.

I can't see by looking at the code how it should be fixed; it's many layers of abstraction & indirection that seem quite opaque to me.

**Comment by lastobelus** [comment]
I figured out a workaround, which was to use a `rule` block with a different name to apply the custom predicate to the collection:

```ruby
    rule(has_at_least_one_song: [:songs]) do | songs |
      songs.has_a_song?
    end
```

This has the disadvantage that the error is not associated with the collection name and I have to look for it explicitly, but at least the rest of my form + bootstrap_form_for doesn't blow up.

**Comment by lastobelus** [comment]
@apotonick I wrote this spec in the context of my application which uses `reform-rails`, but I'm pretty sure that it happens without `reform-rails` installed? Or is it that `form.errors` is intended to only be used in a Rails context, and `form.to_result` otherwise?

**Comment by emaglio** [comment]
@lastobelus just a couple of years late but we should have a fix for this.
Do you still have that code running in your project?
Could you please try the branch https://github.com/trailblazer/reform/tree/emaglio/custom-rule-collection-property-436?

**Comment by emaglio** [comment]
Fixed with https://github.com/trailblazer/reform/pull/493
