### ISSUE TITLE
Collection virtual attribute undefined method error

### ISSUE THREAD

**Issue by lsamon** [trailblazer/reform#461]
### Complete Description of Issue
Environment
Rails 4.2.10

I am currently having issues with Reform virtual attributes for collections. I have three Tables
Application - has_many :documents, belongs_to :applicant
Applicant - has_many :applications
Document - belongs_to :application

```
class Public::CrewApplicationsFinalDetailsForm < Reform::Form
   feature Coercion

   property :id
   validates :id, presence: true

   property :applicant do
     property :bank_bsb_number
     property :bank_account_number
     property :insurance_covered_by_tidyme, type: Types::Form::Bool
     property :insurance
     property :surprising_about_me, virtual: true # this works fine
     property :favorite_things_to_do, virtual: true # this works fine
     property :biography
     ..............................
    collection :documents, populator: -> (fragment:, **) {
       item = documents.find { |doc| doc.id == fragment['id'].to_i }
       item ? item : documents.append(Document.new)
     } do
     property :application_id
     property :document_type
     property :image

     property :insured, virtual: true # This brings an error
     # undefined method `insured' for #<Document:0x007fa046d2d4b0>

     validates :image, presence: true
     validates :application_id, :document_type, presence: true
     validates :image, file_content_type: { allow: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/zip'], message: 'Invalid Filetype: Please upload in image, pdf or doc format' }
  end
```

The view - final_details.html.slim
```
            = f.fields_for :documents, Document.new do |d|
              = d.hidden_field :document_type, value: :insurance
              = d.hidden_field :application_id, value: @application.id
              = d.hidden_field :insured
              .form-group
                #insurance-upload style='display:none'
                  = d.label :image do
                    |Upload a photo of your current public liability insurance
                    sup.asterisk *
                  = d.file_field :image, class: 'form-control'
```

Expected behavior 
To view final_details.html.slim without any erros

Actual behavior
The page breaks and this error appears  # undefined method `insured' for #<Document:0x007fa046d2d4b0> even though **insured** is a virtual attribute under the documents collection.

### System configuration
gem "reform", ">= 2.2.0"
gem "reform-rails"

### Full Backtrace of Exception
NoMethodError - undefined method `insured' for #<Document:0x007fa046d2d4b0>
Did you mean?  insurance!:
  activemodel (4.2.10) lib/active_model/attribute_methods.rb:433:in `method_missing'
  ransack (1.8.2) lib/ransack/helpers/form_builder.rb:10:in `value'
  actionview (4.2.10) lib/action_view/helpers/tags/base.rb:38:in `value_before_type_cast'
  actionview (4.2.10) lib/action_view/helpers/tags/text_field.rb:13:in `block in render'
  actionview (4.2.10) lib/action_view/helpers/tags/text_field.rb:13:in `render'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:826:in `hidden_field'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:1751:in `hidden_field'
  app/views/public/crew_applications/final_details.html.slim:53:in `block (2 levels) in _app_views_public_crew_applications_final_details_html_slim__2975879758442389117_70163159432920'
  actionview (4.2.10) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.10) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.10) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:1925:in `block in fields_for_nested_model'
  actionview (4.2.10) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.10) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.10) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:714:in `fields_for'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:1924:in `fields_for_nested_model'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:1910:in `block in fields_for_with_nested_attributes'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:1908:in `fields_for_with_nested_attributes'
  actionview (4.2.10) lib/action_view/helpers/form_helper.rb:1582:in `fields_for'
  app/views/public/crew_applications/final_details.html.slim:50:in `block in _app_views_public_crew_applications_final_details_html_slim__2975879758442389117_70163159432920'

**Comment by lsamon** [comment]
Apologies, redundant issue #426
