### ISSUE TITLE
Issue with some property names

### ISSUE THREAD

**Issue by mojobiri** [trailblazer/reform#471]
Hi,
I have noticed that there is an issue with some property names: **class**, **model** at least.

```ruby
class AlbumForm < Reform::Form
  property :title, virtual: true
  property :model, virtual: true
  property :class, virtual: true

  validates :title, :model, :class, presence: true
end

model = OpenStruct.new({ title: 'CHV', model: 'Chevrolet', class: 'Middle' })
form = AlbumForm.new(model)
form.validate({})
form.errors.messages
```
I expect no errors.

But instead I'm getting `NoMethodError: undefined method 'expose_class' for nil:NilClass`.
This happens when `property :class` defined.
When `property :model` defined, there is no error, but it also have an impact because it is overrides `form.model` getter and it becomes `nil`.
Any recommendations on how to deal with this?
At the end, I want to get validation errors:
```ruby
form.errors.messages
# => {:class=>["Please enter the Class"], :model=>["Please enter the Model"]}
```

### System configuration
**Reform version**: reform (2.1.0)

### Full Backtrace of Exception (if any)
```
NoMethodError: undefined method `expose_class' for nil:NilClass
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/disposable-0.2.6/lib/disposable/twin/composition.rb:19:in `mapper_for'
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/disposable-0.2.6/lib/disposable/twin/setup.rb:11:in `initialize'
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/reform-2.1.0/lib/reform/contract/validate.rb:3:in `initialize'
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/disposable-0.2.6/lib/disposable/twin/changed.rb:26:in `initialize'
	from (irb):10:in `new'
	from (irb):10
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/denis/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by emaglio** [comment]
@mojobiri 2.1 is quite old - have you tried to update to 2.2.4?

**Comment by mojobiri** [comment]
@emaglio same with reform (2.2.4)

**Comment by emaglio** [comment]
This https://github.com/apotonick/disposable/pull/76 is not really fixing this issue but at least notify the User that `class` cannot be used - this can be fixed but it's not really a priority for us now so I'm adding a note for the 3.0 version.
